import { Award, Shield, TrendingUp } from "lucide-react";

export type SiteConfig = typeof siteConfig;

export const siteConfig = {
	name: "Linkor",
	app: "https://app.linkor.host",
	description:
		"A Linkor oferece serviços para potencializar seus serviços digitais para tudo que seu projeto precisa e uma equipe que está sempre disposta a te levar ao sucesso.",
	promoCard: {
		active: false,
		items: [
			{
				image:
					"https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DV%20WHATSAPP-JfqpYpH7Ye56LN6S0ldMWFHv0Ztgua.png",
				title: "AMD Ryzen™ 9 7900X",
				subtitle: "4.7GHz - Até 5.6 GHz",
				features: [
					"2vCPU Ryzen 9",
					"2GB RAM DDR5",
					"40GB NVME",
					"1 IPv4 (/32)",
					"1 IPv6 (/128)",
					"Windows 2012 Até 2025!",
				],
				price: "50,00",
				originalPrice: "99,00",
				ctaText: "Contratar Agora",
			},
			{
				image:
					"https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natal-linkor-500x500-ovjTWyNV5J1tUBBmy6Gz4K8ofaprLI.png",
				title: "cPanel ECO-5",
				subtitle: "Perfeito para iniciantes",
				features: [
					"Hospedagem para um domínio",
					"5 GB de armazenamento NVMe",
					"1 Conta de e-mail grátis",
					"Tráfego Ilimitado",
					"Litespeed Webserver + QUIC.cloud",
					"Backup semanal",
				],
				price: "6,99",
				ctaText: "Aproveitar Oferta",
				isChristmas: true,
			},
		],
	},
	navItems: [
		{
			label: "Inicio",
			href: "/",
		},
	],
	gameServer: { link: "#planos-servidor-jogos" },
	cpanelPlans: [
		{
			id: "essencial",
			name: "Essencial",
			link: "#",
			price: "29,99",
			annualPrice: "17,99",
			storage: "10 GB SSD",
			bandwidth: "Ilimitado",
			domains: "Tenha sites ilimitados",
			databases: "Bancos de dados Ilimitados",
			features: [
				{ text: "1 Licença cPanel", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "Email @seudominio.com.br", included: true },
				{
					text: "Backup grátis todos os dias",
					included: true,
					tooltip: "Backups automáticos com retenção de 7 dias",
				},
				{ text: "Certificado de segurança SSL", included: true },
				{ text: "Proteção Cloudflare", included: true },
				{ text: "LiteSpeed Web Server", included: true, highlight: false },
				{ text: "Seletor PHP 5.6 a 8.4", included: true },
				{ text: "Migração de site grátis", included: true },
				{ text: "PHP + NodeJS + Ruby + Python", included: true },
				{ text: "Cache avançado", included: true },
				{ text: "Bônus PRO DOWNLOADS", included: true },
				{ text: "IP dedicado", included: false, highlight: true },
				{ text: "Recursos dedicados", included: false, highlight: true },
				{ text: "Suporte prioritário", included: false, highlight: true },
			],
		},
		{
			id: "expansao",
			name: "Expansão",
			link: "#",
			price: "39,99",
			annualPrice: "23,99",
			storage: "50 GB NVMe",
			bandwidth: "Ilimitado",
			domains: "Tenha sites ilimitados",
			databases: "Bancos de dados Ilimitados",
			features: [
				{ text: "1 Licença cPanel", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "Email @seudominio.com.br", included: true },
				{
					text: "Backup grátis todos os dias",
					included: true,
					tooltip: "Backups automáticos com retenção de 7 dias",
				},
				{ text: "Certificado de segurança SSL", included: true },
				{ text: "Proteção Cloudflare", included: true },
				{ text: "LiteSpeed Web Server", included: true, highlight: false },
				{ text: "Seletor PHP 5.6 a 8.4", included: true },
				{ text: "Migração de site grátis", included: true },
				{ text: "PHP + NodeJS + Ruby + Python", included: true },
				{ text: "Cache avançado", included: true },
				{ text: "Bônus PRO DOWNLOADS", included: true },
				{ text: "IP dedicado", included: false, highlight: true },
				{ text: "Recursos dedicados", included: false, highlight: true },
				{ text: "Suporte prioritário", included: true, highlight: true },
			],
			recommended: true,
		},
		{
			id: "executivo",
			name: "Executivo",
			link: "#",
			price: "69,99",
			annualPrice: "41,99",
			storage: "100 GB NVMe",
			bandwidth: "Ilimitado",
			domains: "Tenha sites ilimitados",
			databases: "Bancos de dados Ilimitados",
			features: [
				{ text: "1 Licença cPanel", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "Email @seudominio.com.br", included: true },
				{
					text: "Backup grátis todos os dias",
					included: true,
					tooltip: "Backups automáticos com retenção de 7 dias",
				},
				{ text: "Certificado de segurança SSL", included: true },
				{ text: "Proteção Cloudflare", included: true },
				{ text: "LiteSpeed Web Server", included: true, highlight: false },
				{ text: "Seletor PHP 5.6 a 8.4", included: true },
				{ text: "Migração de site grátis", included: true },
				{ text: "PHP + NodeJS + Ruby + Python", included: true },
				{ text: "Cache avançado", included: true },
				{ text: "Bônus PRO DOWNLOADS", included: true },
				{ text: "IP dedicado", included: true, highlight: true },
				{ text: "Recursos dedicados", included: true, highlight: true },
				{ text: "Suporte prioritário", included: true, highlight: false },
			],
		},
	],
	pleskPlans: [
		{
			id: "basic",
			name: "Basic",
			link: "#",
			price: "24,90",
			annualPrice: "19,90",
			storage: "15 GB SSD NVMe",
			bandwidth: "Ilimitado",
			domains: "2 domínios",
			databases: "10 MySQL",
			features: [
				{ text: "Plesk Obsidian", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "10 Contas de Email", included: true },
				{ text: "Backup Semanal", included: true },
				{ text: "WordPress Toolkit", included: false },
				{ text: "Proteção Imunify360", included: false },
				{ text: "Git integrado", included: true, highlight: true },
				{ text: "Docker suporte", included: false },
				{ text: "Node.js, Python, PHP", included: true },
				{ text: "Migração gratuita", included: true },
			],
		},
		{
			id: "professional",
			name: "Professional",
			link: "#",
			price: "49,90",
			annualPrice: "39,90",
			storage: "30 GB SSD NVMe",
			bandwidth: "Ilimitado",
			domains: "10 domínios",
			databases: "30 MySQL",
			features: [
				{ text: "Plesk Obsidian", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "30 Contas de Email", included: true },
				{ text: "Backup Diário", included: true },
				{ text: "WordPress Toolkit", included: true, highlight: true },
				{ text: "Proteção Imunify360", included: true, highlight: true },
				{ text: "Git integrado", included: true },
				{ text: "Docker suporte", included: true, highlight: true },
				{ text: "Node.js, Python, PHP", included: true },
				{ text: "Migração gratuita", included: true },
				{ text: "CI/CD pipeline", included: true, highlight: true },
				{ text: "Staging environments", included: true },
			],
			recommended: true,
		},
		{
			id: "ultimate",
			name: "Ultimate",
			link: "#",
			price: "89,90",
			annualPrice: "71,90",
			storage: "75 GB SSD NVMe",
			bandwidth: "Ilimitado",
			domains: "Ilimitados",
			databases: "Ilimitados MySQL",
			features: [
				{ text: "Plesk Obsidian", included: true },
				{ text: "Certificado SSL Grátis", included: true },
				{ text: "Contas de Email Ilimitadas", included: true, highlight: true },
				{ text: "Backup Diário", included: true },
				{ text: "WordPress Toolkit Deluxe", included: true, highlight: true },
				{
					text: "Proteção Imunify360 Premium",
					included: true,
					highlight: true,
				},
				{ text: "Git integrado", included: true },
				{ text: "Docker suporte", included: true },
				{ text: "Node.js, Python, PHP", included: true },
				{ text: "Migração gratuita", included: true },
				{ text: "CI/CD pipeline", included: true },
				{ text: "Staging environments", included: true },
				{ text: "IP dedicado", included: true, highlight: true },
				{ text: "Recursos dedicados", included: true, highlight: true },
				{ text: "Suporte prioritário", included: true, highlight: true },
			],
		},
	],
	vpsPlans: [
		{
			id: "ryzen7900",
			name: "AMD Ryzen™ 9 7900X",
			allPlans: "#",
			plans: [
				{
					id: "starter",
					name: "Plano Starter",
					link: "#",
					specs: "2 vCPU • 4GB RAM • 80GB SSD NVMe",
					price: "69,90",
					color: "#F04339",
				},
				{
					id: "advanced",
					name: "Plano 1",
					link: "#",
					specs: "4 vCPU • 8GB RAM • 160GB SSD NVMe",
					price: "129,90",
					color: "#F04339",
				},
				{
					id: "enterprise",
					name: "Plano 2",
					link: "#",
					specs: "8 vCPU • 16GB RAM • 320GB SSD NVMe",
					price: "249,90",
					color: "#F04339",
				},
			],
		},
		{
			id: "ryzen5900",
			name: "AMD Ryzen™ 9 5900X",
			allPlans: "#",
			plans: [
				{
					id: "starter",
					name: "Plano Starter",
					link: "#",
					specs: "2 vCPU • 4GB RAM • 60GB SSD NVMe",
					price: "49,90",
					color: "#F04339",
				},
				{
					id: "advanced",
					name: "Plano 1",
					link: "#",
					specs: "4 vCPU • 8GB RAM • 120GB SSD NVMe",
					price: "99,90",
					color: "#F04339",
				},
				{
					id: "enterprise",
					name: "Plano 2",
					link: "#",
					specs: "6 vCPU • 12GB RAM • 240GB SSD NVMe",
					price: "179,90",
					color: "#F04339",
				},
			],
		},
		{
			id: "intel",
			name: "Intel(R) Xeon(R) Platinum",
			allPlans: "#",
			plans: [
				{
					id: "starter",
					name: "Plano Starter",
					link: "#",
					specs: "4 vCPU • 8GB RAM • 120GB SSD NVMe",
					price: "89,90",
					color: "#3B82F6",
				},
				{
					id: "advanced",
					name: "Plano 1",
					link: "#",
					specs: "8 vCPU • 16GB RAM • 240GB SSD NVMe",
					price: "159,90",
					color: "#3B82F6",
				},
				{
					id: "enterprise",
					name: "Plano 2",
					link: "#",
					specs: "16 vCPU • 32GB RAM • 480GB SSD NVMe",
					price: "299,90",
					color: "#3B82F6",
				},
			],
		},
	],
	partners: [
		{
			name: "Envato Elements",
			logo: "/conteudos/provider_envato.svg",
			width: 180,
			height: 60,
		},
		{
			name: "Freepik",
			logo: "/conteudos/provider_freepik.svg",
			width: 70,
			height: 20,
		},

		{
			name: "Flaticon",
			logo: "/conteudos/provider_flaticon.svg",
			width: 180,
			height: 60,
		},
		{
			name: "GPL Vault",
			logo: "/conteudos/provider_gplvault.svg",
			width: 180,
			height: 60,
		},
		{
			name: "Storyblocks",
			logo: "/conteudos/provider_storyblocks.png",
			width: 180,
			height: 60,
		},
		{
			name: "Motion Array",
			logo: "/conteudos/provider_motionarray.svg",
			width: 180,
			height: 60,
		},
		{
			name: "IconScout",
			logo: "/conteudos/provider_iconscout.png",
			width: 180,
			height: 60,
		},
		{
			name: "GPLZONE",
			logo: "/conteudos/provider_gplzone.svg",
			width: 180,
			height: 60,
		},
		{
			name: "FestingerVault",
			logo: "/conteudos/provider_festingervault.svg",
			width: 180,
			height: 60,
		},
		{
			name: "Artlist",
			logo: "/conteudos/provider_artlist.svg",
			width: 180,
			height: 60,
		},
		{
			name: "ProductionCrate",
			logo: "/conteudos/provider_productioncrate.svg",
			width: 180,
			height: 60,
		},
	],
	categories: [
		{
			title: "IMAGENS, VETORES E FOTOS",
			count: "+20 milhões",
			description:
				"Inclui fotos, vetores, vídeos, imagens, PSD e modelos gráficos.",
		},
		{
			title: "MODELOS, FONTES E ÁUDIOS",
			count: "+900.000",
			description:
				"Inclui apresentações, banco de vídeos, fontes e arquivos 3D.",
		},
		{
			title: "TEMAS E PLUGINS WORDPRESS",
			count: "+20.000",
			description:
				"Inclui temas e plugins premium WordPress e extensões para ecommerce.",
		},
	],
	testimonials: [
		{
			id: 1,
			name: "Miguel Oliveira",
			role: "CEO",
			company: "TechSolutions",
			image: "/professional-headshot.png",
			rating: 5,
			text: "Desde que migramos para a Linkor, os tempos de carregamento do nosso site diminuíram em 70%. A infraestrutura deles é sólida e a equipe de suporte é incrivelmente responsiva. Melhor decisão que tomamos para nosso e-commerce em crescimento.",
		},
		{
			id: 2,
			name: "Fernanda Lima",
			role: "CTO",
			company: "WebDev Brasil",
			image:
				"https://hebbkx1anhila5yf.public.blob.vercel-storage.com/FRAME-HOSPEDAGEMDESITES-zh2E6tATHuF7TpcnhHWfJBeTV1ntJq.png",
			rating: 5,
			text: "Nossa experiência com a Linkor tem sido fantástica. Desde a hospedagem até as soluções empresariais, cada aspecto foi tratado com dedicação. Nosso site em WordPress nunca funcionou tão bem.",
		},
		{
			id: 3,
			name: "Carlos Santos",
			role: "Fundador",
			company: "AppStart",
			image: "/professional-man-headshot.png",
			rating: 5,
			text: "À medida que nossa startup cresceu de 10.000 para 1 milhão de usuários, a Linkor cresceu conosco sem esforço. Sua infraestrutura de escalonamento automático lidou com picos de tráfego perfeitamente.",
		},
		{
			id: 4,
			name: "Ana Beatriz",
			role: "Diretora de Marketing",
			company: "E-commerce Express",
			image: "/professional-woman-headshot.png",
			rating: 5,
			text: "A velocidade de carregamento do nosso site melhorou drasticamente após migrarmos para a Linkor. Nossas taxas de conversão aumentaram 35% apenas por causa da melhoria no desempenho. O suporte técnico é excepcional.",
		},
		{
			id: 5,
			name: "Roberto Mendes",
			role: "Desenvolvedor Full Stack",
			company: "DevHouse",
			image: "/professional-man-headshot.png",
			rating: 4,
			text: "Como desenvolvedor, aprecio muito as ferramentas que a Linkor oferece. O ambiente de staging, os pipelines de CI/CD e a facilidade de implantação tornaram meu fluxo de trabalho muito mais eficiente.",
		},
		{
			id: 6,
			name: "Juliana Costa",
			role: "Gerente de Projetos",
			company: "Agência Digital",
			image: "/professional-woman-headshot.png",
			rating: 5,
			text: "Gerenciar múltiplos projetos web se tornou muito mais fácil com a Linkor. O painel de controle intuitivo e as ferramentas de monitoramento nos ajudam a manter tudo funcionando perfeitamente.",
		},
		{
			id: 7,
			name: "Marcelo Alves",
			role: "Proprietário",
			company: "Loja Virtual MegaShop",
			image: "/professional-headshot.png",
			rating: 5,
			text: "Minha loja virtual nunca esteve tão estável. Mesmo durante a Black Friday, com tráfego 10x maior que o normal, o site permaneceu rápido e responsivo. A proteção DDoS da Linkor realmente funciona!",
		},
		{
			id: 8,
			name: "Camila Ferreira",
			role: "Arquiteta de Software",
			company: "TechInnovate",
			image: "/professional-woman-headshot.png",
			rating: 4,
			text: "A flexibilidade da infraestrutura da Linkor nos permitiu escalar conforme necessário. Começamos com um plano básico e crescemos gradualmente sem nenhum tempo de inatividade durante as migrações.",
		},
		{
			id: 9,
			name: "Paulo Henrique",
			role: "Diretor de TI",
			company: "Grupo Empresarial",
			image: "/professional-man-headshot.png",
			rating: 5,
			text: "Após avaliar vários provedores de hospedagem, escolhemos a Linkor pela combinação de desempenho, segurança e custo-benefício. Três anos depois, continuamos extremamente satisfeitos com nossa decisão.",
		},
	],
	googleReviews: {
		qntdReviews: "1.247",
		stars: {
			5: "85%",
			4: "10%",
			3: "3%",
			2: "1%",
			1: "1%",
		},
		averageRating: "4.8",
		Reputation: "Ótima",
		Index: "9.8",
		Answered: "100%",
		Solution: "98.4%",
		description:
			"A Linkor demonstra excelência no atendimento ao cliente, com tempo médio de resposta de 1h32min e resolução de problemas em menos de 24 horas.",
		subDescription: "— Análise Reclame Aqui, 2024",
		reviews: [
			{
				name: "Ricardo Almeida",
				star: 5,
				description:
					"Serviço excepcional! O suporte técnico é rápido e eficiente. Meu site nunca esteve tão rápido.",
			},
			{
				name: "Mariana Costa",
				star: 4,
				description:
					"Migrei meu e-commerce para a Linkor e a diferença foi impressionante. Velocidade, estabilidade e suporte de primeira.",
			},
		],
		certifications: [
			{
				title: "Melhor Hospedagem 2023",
				subTitle: "TechMasters Awards",
				icon: Award,
			},
			{
				title: "Melhor Custo-Benefício",
				subTitle: "Cloud Computing Brasil",
				icon: TrendingUp,
			},
			{
				title: "Certificação",
				subTitle: "Segurança da Informação",
				icon: Shield,
			},
		],
	},
};
